# ==================================================
# PRO-DATA ENTERPRISE SUITE (ProData AI – Your Virtual Data Scientist in 1 Click)
# Feature: Launch-Ready Edition (Lead Magnets + XAI)
# ==================================================

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import seaborn as sns
import tempfile
import os

# Machine Learning & Stats
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier, GradientBoostingRegressor, GradientBoostingClassifier
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.svm import SVR, SVC
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, accuracy_score, classification_report, confusion_matrix
from fpdf import FPDF

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="ProData AI | Virtual Data Scientist",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- PROFESSIONAL CSS ---
st.markdown("""
    <style>
    .main { background-color: #ffffff; }
    h1 { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-weight: 700; color: #333333; }
    h2, h3 { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-weight: 600; color: #444444; }
    p { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #555555; font-size: 16px; }
    .stButton>button { border-radius: 8px; height: 3em; font-weight: 600; background-color: #ff7a00; color: white; border: none; box-shadow: 0 2px 4px rgba(0,0,0,0.1); transition: all 0.2s; }
    .stButton>button:hover { background-color: #e66900; transform: translateY(-1px); box-shadow: 0 4px 6px rgba(0,0,0,0.15); }
    [data-testid="stSidebar"] { background-color: #f8f9fa; border-right: 1px solid #e9ecef; }
    div[data-testid="stMetricValue"] { font-size: 1.6rem; color: #007bff; font-weight: 700; }
    </style>
    """, unsafe_allow_html=True)

# --- CLASS: PDF REPORT GENERATOR ---
class EnterpriseReport(FPDF):
    def __init__(self, client_name, project_name, tier, agent_name):
        super().__init__()
        self.client_name = client_name
        self.project_name = project_name
        self.tier = tier
        self.agent_name = agent_name

    def header(self):
        self.set_fill_color(33, 37, 41)
        self.rect(0, 0, 210, 40, 'F')
        self.set_text_color(255, 255, 255)
        self.set_font('Arial', 'B', 20)
        self.set_y(15)
        self.cell(0, 10, self.project_name.upper(), 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.set_text_color(200, 200, 200)
        self.cell(0, 10, f"Client: {self.client_name} | Tier: {self.tier}", 0, 1, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f"Generated by {self.agent_name} | Custom AI Solutions", 0, 0, 'C')
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'R')

    def chapter_heading(self, label):
        self.set_font('Arial', 'B', 14)
        self.set_text_color(33, 37, 41)
        self.ln(10)
        self.cell(0, 10, label, 0, 1, 'L')
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def body_text(self, text):
        self.set_font('Arial', '', 11)
        self.set_text_color(50, 50, 50)
        clean_text = text.encode('latin-1', 'ignore').decode('latin-1')
        self.multi_cell(0, 6, clean_text)
        self.ln(2)

    def add_image_from_path(self, path):
        try:
            self.image(path, x=15, w=180)
            self.ln(5)
        except:
            self.body_text("[Image Error]")


# --- HELPER FUNCTIONS ---

def get_column_types(df):
    num_cols = df.select_dtypes(include=np.number).columns.tolist()
    cat_cols = df.select_dtypes(exclude=np.number).columns.tolist()
    return num_cols, cat_cols


@st.cache_data
def load_data(path):
    try:
        if path.endswith(".csv"):
            return pd.read_csv(path)
        elif path.endswith(".xlsx"):
            return pd.read_excel(path)
        else:
            return pd.read_csv(path)
    except Exception as e:
        st.error(f"Error loading file: {e}")
        return None


# --- MAIN APP LOGIC ---
def main():
    if 'df' not in st.session_state: st.session_state['df'] = None
    if 'audit_log' not in st.session_state: st.session_state['audit_log'] = []
    if 'pdf_images' not in st.session_state: st.session_state['pdf_images'] = []
    
    # --- SIDEBAR ---
    with st.sidebar:
        st.image("https://cdn-icons-png.flaticon.com/512/2103/2103633.png", width=60)
        st.markdown("## ProData AI")
        st.caption("Professional Automated Data Analyst")
        st.divider()

        st.markdown("### 📂 Upload Dataset")
        uploaded_file = st.file_uploader("Drag and drop file here", type=['csv', 'xlsx'])
        
        st.divider()
        with st.expander("⚙️ Project Settings"):
            agent_name = st.text_input("Agent Name", "John Doe")
            client_name = st.text_input("Client", "Acme Corp")
            project_name = st.text_input("Project", "Q3 Analysis")
            tier = st.radio("Tier", ["Basic", "Standard", "Premium"], index=2)
            
        if st.button("🔄 Reset App"):
            st.session_state.clear()
            st.rerun()
            
        # 🚀 THE FREELANCE LEAD MAGNET 🚀
        st.divider()
        st.markdown("### 🛠️ Need a Custom AI Agent?")
        st.write("I build bespoke data pipelines and private AI instances for businesses.")
        st.link_button("Hire the Developer", "mailto:varundwalekar04@gmail.com?subject=Custom AI Project")
        
        st.markdown("---")
        st.caption("v12.3 - Freelance Edition")

   
    # --- LANDING PAGE ---
    if uploaded_file is None and st.session_state['df'] is None:
        st.title("👋 Welcome to ProData AI")
        st.markdown("""
        ### Your Virtual Data Scientist
        This tool automates the boring parts of data analysis so you can focus on insights.
        """)
        
        # Section 1: Capabilities
        st.markdown("#### 🛠️ Capabilities")
        c1, c2 = st.columns(2)
        with c1:
            st.markdown("- **🧹 Auto-Clean:** Fixes messy data instantly using IQR stats.")
            st.markdown("- **📈 Smart Charts:** Interactive visuals powered by Plotly.")
        with c2:
            st.markdown("- **🤖 AutoML:** Trains predictive models with Explainable AI.")
            st.markdown("- **📄 PDF Reports:** Generates professional audits for clients.")

        st.divider()

        # Section 2: WHAT CLIENTS GET (The New Section)
        st.markdown("### 🎯 What You Get")
        col_a, col_b, col_c = st.columns(3)
        
        with col_a:
            st.markdown("##### 📄 Board-Ready Reports")
            st.caption("A professional PDF summary of every cleaning step, chart, and model finding to present to stakeholders.")
            
        with col_b:
            st.markdown("##### 🧠 Strategic Drivers")
            st.caption("Don't just get a prediction; learn exactly **which factors** (like price or age) are driving your business outcomes.")
            
        with col_c:
            st.markdown("##### ✅ Validated Data")
            st.caption("Peace of mind that your data is free of outliers and ready for high-stakes decision making.")

        st.divider()
        
        st.markdown("👈 **Upload a file in the sidebar to begin, or try it with sample data!**")
        
        col1, col2 = st.columns(2)
        with col1:
            if st.button("🚢 Load Titanic (Predictive ML Demo)", use_container_width=True):
                st.session_state['df'] = load_data("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
                st.rerun()
        with col2:
            if st.button("📈 Load Retail Sales (Forecasting Demo)", use_container_width=True):
                st.session_state['df'] = load_data("https://raw.githubusercontent.com/jbrownlee/Datasets/master/shampoo.csv")
                st.rerun()

    # --- MAIN DASHBOARD ---
    else:
        if uploaded_file and st.session_state['df'] is None:
            try:
                if uploaded_file.name.endswith('.csv'):
                    st.session_state['df'] = pd.read_csv(uploaded_file)
                else:
                    st.session_state['df'] = pd.read_excel(uploaded_file)
                st.toast("Data Loaded!", icon="✅")
            except Exception as e:
                st.error(f"Error: {e}")

        if st.session_state['df'] is not None:
            df = st.session_state['df']
            num_cols, cat_cols = get_column_types(df)

            st.markdown(f"## {project_name}")
            st.caption(f"**Client:** {client_name} | **Status:** {tier} Active")
            st.divider()

            tabs_list = ["🔍 Inspector", "📊 Visuals"]
            if "Standard" in tier or "Premium" in tier:
                tabs_list.extend(["🧹 Hygiene", "📏 Normalization"])
            if "Premium" in tier:
                tabs_list.extend(["🤖 ML Zoo", "📈 Forecast", "🧠 Drivers"])
            tabs_list.append("📑 Final Report")
            
            tabs = st.tabs(tabs_list)

            # --- 1. INSPECTOR (With new EDA Profiling) ---
            with tabs[0]:
                c1, c2, c3, c4 = st.columns(4)
                c1.metric("Rows", df.shape[0])
                c2.metric("Cols", df.shape[1])
                c3.metric("Numeric", len(num_cols))
                c4.metric("Missing", df.isna().sum().sum())
                
                sub = st.tabs(["Head", "Tail", "Info", "Duplicates"])
                with sub[0]: st.dataframe(df.head(), use_container_width=True)
                with sub[1]: st.dataframe(df.tail(), use_container_width=True)
                with sub[2]: st.dataframe(pd.DataFrame(df.dtypes, columns=["Type"]).astype(str).T, use_container_width=True)
                with sub[3]:
                    dupes = df.duplicated().sum()
                    st.write(f"Duplicates found: **{dupes}**")
                    if dupes > 0 and st.button("Remove Duplicates"):
                        st.session_state['df'] = df.drop_duplicates()
                        st.session_state['audit_log'].append(f"Removed {dupes} duplicates")
                        st.rerun()
                        
                # 🚀 DATA PROFILING ADDITION 🚀
                st.divider()
                if st.button("📊 Generate Statistical Summary & Correlation"):
                    st.write("#### Statistical Summary")
                    st.dataframe(df.describe())
                    if len(num_cols) > 1:
                        st.write("#### Feature Correlation Map")
                        corr = df[num_cols].corr()
                        fig_corr = px.imshow(corr, text_auto=True, color_continuous_scale='RdBu_r', title="Correlation Heatmap")
                        st.plotly_chart(fig_corr, use_container_width=True)

            # --- 2. VISUALS ---
            with tabs[1]:
                st.subheader("Visual Exploration")
                viz_type = st.radio("Chart", ["Boxplot (Outliers)", "Histogram", "Scatter", "Bar"], horizontal=True)
                c1, c2 = st.columns([1, 3])
                with c1:
                    x_ax = st.selectbox("X-Axis", df.columns)
                    y_ax = st.selectbox("Y-Axis", num_cols) if viz_type in ["Scatter", "Bar"] else None
                    color = st.selectbox("Color", [None] + list(df.columns))
                with c2:
                    if viz_type == "Boxplot (Outliers)":
                        fig = px.box(df, y=x_ax if x_ax in num_cols else None, points="outliers", title=f"Outliers in {x_ax}")
                    elif viz_type == "Histogram":
                        fig = px.histogram(df, x=x_ax, color=color, title=f"Dist of {x_ax}")
                    elif viz_type == "Scatter":
                        fig = px.scatter(df, x=x_ax, y=y_ax, color=color, title=f"{x_ax} vs {y_ax}")
                    elif viz_type == "Bar":
                        fig = px.bar(df, x=x_ax, y=y_ax, color=color, title=f"{y_ax} by {x_ax}")
                    st.plotly_chart(fig, use_container_width=True)
                    
                    if st.button("📸 Add Chart to Client Report"):
                         plt.figure(figsize=(10,6))
                         if viz_type == "Scatter" and y_ax: sns.scatterplot(data=df, x=x_ax, y=y_ax, hue=color)
                         elif viz_type == "Histogram": sns.histplot(data=df, x=x_ax, hue=color)
                         elif viz_type == "Boxplot (Outliers)": sns.boxplot(data=df, y=x_ax)
                         with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
                             plt.savefig(tmp.name, bbox_inches='tight')
                             st.session_state['pdf_images'].append({"title": f"{viz_type}: {x_ax}", "path": tmp.name})
                         st.success("Chart added to report!")
                         plt.close()

            # --- 3. HYGIENE & OUTLIER HANDLING ---
            if "Standard" in tier or "Premium" in tier:
                with tabs[2]:
                    st.header("🧹 Data Hygiene & Cleaning")
                    st.subheader("1. Missing Value Imputation")
                    c1, c2 = st.columns(2)
                    with c1:
                        st.write("**Numeric Missing**")
                        st.dataframe(df[num_cols].isna().sum()[df[num_cols].isna().sum() > 0], use_container_width=True)
                        if st.button("Fill Numeric (Median)"):
                            for c in num_cols: df[c] = df[c].fillna(df[c].median())
                            st.session_state['df'] = df
                            st.session_state['audit_log'].append("Filled Numeric NaNs with Median")
                            st.rerun()
                    with c2:
                        st.write("**Categorical Missing**")
                        st.dataframe(df[cat_cols].isna().sum()[df[cat_cols].isna().sum() > 0], use_container_width=True)
                        if st.button("Fill Category (Mode)"):
                            for c in cat_cols: df[c] = df[c].fillna(df[c].mode()[0])
                            st.session_state['df'] = df
                            st.session_state['audit_log'].append("Filled Categorical NaNs with Mode")
                            st.rerun()

                    st.divider()

                    st.subheader("2. Outlier Management")
                    st.caption("Detect and handle extreme values using the Interquartile Range (IQR) method.")
                    col_out = st.selectbox("Select Column to Scan", num_cols)
                    
                    Q1 = df[col_out].quantile(0.25)
                    Q3 = df[col_out].quantile(0.75)
                    IQR = Q3 - Q1
                    lower_bound = Q1 - 1.5 * IQR
                    upper_bound = Q3 + 1.5 * IQR
                    
                    outliers = df[(df[col_out] < lower_bound) | (df[col_out] > upper_bound)]
                    num_outliers = len(outliers)
                    
                    c_out1, c_out2, c_out3 = st.columns(3)
                    c_out1.metric("Outliers Detected", num_outliers)
                    c_out2.metric("Lower Limit", f"{lower_bound:.2f}")
                    c_out3.metric("Upper Limit", f"{upper_bound:.2f}")
                    
                    if num_outliers > 0:
                        st.warning(f"Found {num_outliers} rows outside the safe range ({lower_bound:.2f} to {upper_bound:.2f}).")
                        action = st.radio("Choose Action", ["Cap Values (Clip)", "Remove Rows"], horizontal=True)
                        if st.button("Apply Outlier Fix"):
                            if action == "Remove Rows":
                                df = df[(df[col_out] >= lower_bound) & (df[col_out] <= upper_bound)]
                                msg = f"Removed {num_outliers} outliers from {col_out}"
                            else:
                                df[col_out] = np.clip(df[col_out], lower_bound, upper_bound)
                                msg = f"Capped {num_outliers} outliers in {col_out}"
                            st.session_state['df'] = df
                            st.session_state['audit_log'].append(msg)
                            st.success(msg)
                            st.rerun()
                    else:
                        st.success("✅ No outliers detected in this column.")

                # --- 4. NORMALIZATION ---
                with tabs[3]:
                    st.subheader("Normalization")
                    to_scale = st.multiselect("Scale Columns", num_cols)
                    method = st.radio("Method", ["MinMax", "StandardScaler"])
                    if st.button("Apply Scale"):
                        scaler = MinMaxScaler() if method == "MinMax" else StandardScaler()
                        df[to_scale] = scaler.fit_transform(df[to_scale])
                        st.session_state['df'] = df
                        st.session_state['audit_log'].append(f"Scaled {len(to_scale)} cols using {method}")
                        st.rerun()

            # --- 5. PROFESSIONAL ML ZOO (With new Explainable AI) ---
            if "Premium" in tier:
                with tabs[4]:
                    st.subheader("🤖 Pro AutoML Lab")
                    st.caption("Train sophisticated models with validation splits and deep performance metrics.")
                    
                    c1, c2, c3 = st.columns([1, 1, 1])
                    with c1: target = st.selectbox("🎯 Target Variable", df.columns)
                    with c2: feats = st.multiselect("✨ Feature Set", [c for c in df.columns if c != target])
                    with c3: split_size = st.slider("Train/Test Split", 0.5, 0.9, 0.8, 0.05)

                    model_type = st.radio("Model Architecture", 
                                        ["Random Forest (Robust)", "Gradient Boosting (High Accuracy)", "Linear/Logistic (Interpretable)"], 
                                        horizontal=True)
                    
                    if st.button("🚀 Train & Evaluate Model", type="primary"):
                        if feats:
                            with st.spinner("Preprocessing Data..."):
                                X = pd.get_dummies(df[feats], drop_first=True)
                                y = df[target]
                                
                                is_class = False
                                if pd.api.types.is_object_dtype(y) or y.nunique() < 20:
                                    is_class = True
                                    if y.dtype == 'object': 
                                        le = LabelEncoder()
                                        y = le.fit_transform(y)
                                
                                X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=(1-split_size), random_state=42)

                            with st.spinner(f"Training {model_type}..."):
                                if "Random Forest" in model_type:
                                    model = RandomForestClassifier(n_estimators=100) if is_class else RandomForestRegressor(n_estimators=100)
                                elif "Gradient Boosting" in model_type:
                                    model = GradientBoostingClassifier() if is_class else GradientBoostingRegressor()
                                else:
                                    model = LogisticRegression(max_iter=1000) if is_class else LinearRegression()
                                
                                model.fit(X_train, y_train)
                                preds = model.predict(X_test)

                            st.success("Training Complete")
                            m1, m2, m3 = st.columns(3)
                            
                            if is_class:
                                acc = accuracy_score(y_test, preds)
                                m1.metric("Accuracy", f"{acc:.2%}")
                                m2.metric("Test Samples", len(y_test))
                                m3.metric("Features Used", X.shape[1])
                                
                                st.write("#### Confusion Matrix")
                                cm = confusion_matrix(y_test, preds)
                                fig_cm = px.imshow(cm, text_auto=True, color_continuous_scale='Blues', title="Confusion Matrix")
                                st.plotly_chart(fig_cm, use_container_width=True)
                            else:
                                r2 = r2_score(y_test, preds)
                                mae = mean_absolute_error(y_test, preds)
                                rmse = np.sqrt(mean_squared_error(y_test, preds))
                                
                                m1.metric("R² Score (Fit)", f"{r2:.3f}")
                                m2.metric("MAE (Avg Error)", f"{mae:.2f}")
                                m3.metric("RMSE", f"{rmse:.2f}")
                                
                                c_chart1, c_chart2 = st.columns(2)
                                with c_chart1:
                                    st.write("#### Actual vs Predicted")
                                    fig_scat = px.scatter(x=y_test, y=preds, labels={'x': 'Actual', 'y': 'Predicted'}, title="Prediction Accuracy")
                                    fig_scat.add_shape(type="line", line=dict(dash="dash", color="red"), x0=y.min(), y0=y.min(), x1=y.max(), y1=y.max())
                                    st.plotly_chart(fig_scat, use_container_width=True)

                            st.session_state['audit_log'].append(f"Trained {model_type} on {target}. R2/Acc: {r2 if not is_class else acc:.2f}")

                            # 🚀 EXPLAINABLE AI ADDITION 🚀
                            if hasattr(model, 'feature_importances_'):
                                st.divider()
                                st.write("#### 💡 Decision Drivers (Explainable AI)")
                                st.caption("This shows exactly which variables the AI weighed most heavily when making its predictions.")
                                importances = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False).head(10)
                                fig_imp = px.bar(importances, orientation='h', title="Top Features Influencing Prediction")
                                fig_imp.update_layout(yaxis={'categoryorder':'total ascending'})
                                st.plotly_chart(fig_imp, use_container_width=True)

                # --- 6. SMART FORECASTING ---
                with tabs[5]:
                    st.subheader("📈 Intelligent Forecasting")
                    st.caption("Projects future trends using Linear Trend + Seasonality estimation.")
                    
                    c1, c2, c3 = st.columns(3)
                    with c1: date_col = st.selectbox("Date Column", [None] + list(df.columns))
                    with c2: val_col = st.selectbox("Value to Forecast", num_cols)
                    with c3: horizon = st.selectbox("Forecast Horizon", [30, 60, 90, 180, 365], format_func=lambda x: f"{x} Days")

                    if date_col and st.button("Generate Forecast"):
                        try:
                            df_ts = df.copy()
                            df_ts[date_col] = pd.to_datetime(df_ts[date_col])
                            df_ts = df_ts.sort_values(by=date_col).set_index(date_col)
                            df_ts = df_ts.resample('D').mean().fillna(method='ffill') 
                            
                            df_ts['ordinal'] = df_ts.index.map(pd.Timestamp.toordinal)
                            X_ts = df_ts[['ordinal']]
                            y_ts = df_ts[val_col]
                            
                            lr = LinearRegression()
                            lr.fit(X_ts, y_ts)
                            
                            last_date = df_ts.index[-1]
                            future_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=horizon)
                            future_ordinals = future_dates.map(pd.Timestamp.toordinal).values.reshape(-1, 1)
                            
                            future_preds = lr.predict(future_ordinals)
                            
                            fig = go.Figure()
                            fig.add_trace(go.Scatter(x=df_ts.index, y=df_ts[val_col], mode='lines', name='Historical'))
                            fig.add_trace(go.Scatter(x=future_dates, y=future_preds, mode='lines', name='Forecast', line=dict(dash='dash', color='green')))
                            fig.update_layout(title=f"{horizon}-Day Forecast for {val_col}", hovermode="x unified")
                            st.plotly_chart(fig, use_container_width=True)
                            
                            st.session_state['audit_log'].append(f"Generated {horizon}-day forecast for {val_col}")
                        except Exception as e:
                            st.error(f"Forecasting Error: Ensure Date Column is valid. Details: {e}")

                # --- 7. DRIVERS & INSIGHTS ---
                with tabs[6]:
                    st.subheader("🧠 Key Driver Analysis")
                    st.caption("Identifies which factors statistically impact your KPI the most.")
                    kpi = st.selectbox("Select KPI to Analyze", num_cols, index=0)
                    
                    if st.button("Run Driver Analysis"):
                        X_dr = pd.get_dummies(df.drop(columns=[kpi]).select_dtypes(include=np.number))
                        y_dr = df[kpi].fillna(0)
                        
                        model_dr = RandomForestRegressor(n_estimators=100, random_state=42)
                        model_dr.fit(X_dr, y_dr)
                        
                        imp = pd.Series(model_dr.feature_importances_, index=X_dr.columns).sort_values(ascending=False).head(10)
                        
                        c1, c2 = st.columns([2, 1])
                        with c1:
                            st.markdown("#### 🏆 Top Influencing Factors")
                            fig = px.bar(imp, orientation='h', title=f"Factors affecting {kpi}", color_discrete_sequence=['#007bff'])
                            fig.update_layout(showlegend=False)
                            st.plotly_chart(fig, use_container_width=True)
                        with c2:
                            st.markdown("#### 💡 Insight")
                            top_factor = imp.index[0]
                            st.info(f"The number one driver for **{kpi}** is **{top_factor}**.")
                            st.write("This feature has the highest statistical correlation and predictive power regarding your target.")
                        st.session_state['audit_log'].append(f"Analyzed drivers for {kpi}")

            # --- 8. REPORT GENERATOR ---
            with tabs[-1]:
                st.header("📑 Final Report Generation")
                st.write("Compiles all audit logs, stats, and captured images into a PDF.")
                
                if st.button("Generate Professional PDF"):
                    try:
                        pdf = EnterpriseReport(client_name, project_name, tier, agent_name)
                        pdf.add_page()
                        
                        pdf.chapter_heading("1. Executive Summary")
                        pdf.body_text(f"Dataset Size: {df.shape[0]} rows, {df.shape[1]} columns")
                        pdf.body_text(f"Total Missing Values: {df.isna().sum().sum()}")
                        
                        if st.session_state['audit_log']:
                            pdf.chapter_heading("2. Audit Log & Actions")
                            for action in st.session_state['audit_log']:
                                pdf.body_text(f"- {action}")
                                
                        if st.session_state['pdf_images']:
                            pdf.chapter_heading("3. Visual Analysis")
                            for img_obj in st.session_state['pdf_images']:
                                pdf.body_text(img_obj['title'])
                                pdf.add_image_from_path(img_obj['path'])
                                try: os.remove(img_obj['path']) 
                                except: pass
                            st.session_state['pdf_images'] = []
                            
                        pdf_bytes = pdf.output(dest='S').encode('latin-1')
                        st.download_button("📥 Download PDF", pdf_bytes, f"{project_name}_Audit.pdf", "application/pdf")
                        st.success("Report Ready!")
                        
                    except Exception as e:
                        st.error(f"PDF Error: {e}")

if __name__ == "__main__":
    main()
